### ISSUE TITLE
Error when running yarn

### ISSUE THREAD

**Issue by niemasd** [veg/hivtrace-viz#118]
Hi folks, when I try setting up the environment as per the README, I get the following error message when I run `yarn`:

```
$ yarn
yarn install v1.22.19
[1/5] Validating package.json...
error hivtrace-viz@1.1.1: The engine "node" is incompatible with this module. Expected version ">=17". Got "10.19.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I then tried `yarn --ignore-engines`, which bypassed this specific error, but now I get the following:

```
$ yarn --ignore-engines
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "babel-preset-react-hmre > redbox-react@1.6.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0-beta || ^16.0.0".
warning "babel-preset-react-hmre > redbox-react@1.6.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0-beta || ^16.0.0".
warning " > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
warning "font-awesome-webpack > less-loader@2.2.3" has unmet peer dependency "less@^2.3.1".
warning " > font-awesome-webpack-4@1.0.0" has unmet peer dependency "font-awesome@>=4.3.0".
warning "font-awesome-webpack-4 > css-loader@1.0.1" has incorrect peer dependency "webpack@^4.0.0".
warning "font-awesome-webpack-4 > less-loader@4.1.0" has unmet peer dependency "less@^2.3.1 || ^3.0.0".
warning "font-awesome-webpack-4 > less-loader@4.1.0" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning " > postcss-loader@7.0.2" has unmet peer dependency "postcss@^7.0.0 || ^8.0.1".
warning " > react-test-renderer@15.7.0" has unmet peer dependency "react@^15.7.0".
[4/4] Building fresh packages...
[1/7] ⠈ @fortawesome/fontawesome-free
[2/7] ⠈ @fortawesome/fontawesome-common-types
[3/7] ⠈ node-sass
[-/7] ⠈ waiting...
error /workspaces/hivtrace-viz/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments: 
Directory: /workspaces/hivtrace-viz/node_modules/node-sass
Output:
/workspaces/hivtrace-viz/node_modules/@npmcli/fs/lib/fs.js:6
const fsSync = Object.fromEntries(Object.entries(fs).filter(([k, v]) =>
                      ^

TypeError: Object.fromEntries is not a function
    at Object.<anonymous> (/workspaces/hivtrace-viz/node_modules/@npmcli/fs/lib/fs.js:6:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
```

For context, I'm running this in a Docker environment set up from the base Ubuntu 20.04 image with the following command to install dependencies:

```bash
apt-get update && apt-get -y upgrade && \
    DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y git npm && \
    npm install --global yarn
```

**Comment by stevenweaver** [comment]
Hi @niemasd, I'm testing with [Node 18](https://github.com/veg/hivtrace-viz/blob/master/.github/workflows/nodejs.yml#L18). I'm also using [Vercel](https://vercel.com/veg/hivtrace-viz/BxrY4iEy83zrtfYQcxo1HfbG9EVL) for deployment testing. I can add later versions of Node to the build matrix to track later versions.

**Comment by niemasd** [comment]
@liamxg I was able to do it using [nvm](https://github.com/nvm-sh/nvm):

https://github.com/veg/hivtrace-viz/blob/b1db43f5c8790b42815b45c34ecf2f1c43691297/Dockerfile#L7-L11
